### ISSUE TITLE
Error when trying to send any messages

### ISSUE THREAD

**Issue by Esc2020** [CuteNekoOwO/FabricTgBridge#1]
Error when trying to send any messages to a group from server chat with no response from a bot. And no response when sending messages in group to server, but /cmd command works.
All libraries are installed and everything configured properly, but i am using Quilt that may be a reason.

Error:
[13:11:21] [Server thread/INFO]: <minecraft_esc> 123
[13:11:21] [DefaultDispatcher-worker-2/ERROR]: Uncaught exception in thread "DefaultDispatcher-worker-2"
retrofit2.HttpException: HTTP 400 
        at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53) ~[transformed-mod-tgbridge.i0:0/:?]
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161) ~[transformed-mod-tgbridge.i0:0/:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[transformed-mod-tgbridge.i0:0/:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[transformed-mod-tgbridge.i0:0/:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
        at java.lang.Thread.run(Thread.java:1589) ~[?:?]
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException

full log:
[latest.log](https://github.com/CuteNekoOwO/FabricTgBridge/files/10823222/latest.log)

**Comment by MeowBot233** [comment]
Provide your mod config pls (hide your bot token).
Have you modified the telegramFormat? Wrong format can lead to http 400 errors.

**Comment by MeowBot233** [comment]
Closed for inactivity. If you would like to provide your configuration file for debug, feel free to reopen.
