### ISSUE TITLE
Unable to send any message in chat 

### ISSUE THREAD

**Issue by Listum** [CuteNekoOwO/FabricTgBridge#2]
Version: **1.19.2**
Loader: **Quilt 0.18.3-pre.2**
Additional chat mods: **NoChatReports**

Logs: `[12:09:33] [Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.NoSuchMethodError: 'net.minecraft.class_2561 net.minecraft.class_7471.method_46291()'
        at cuteneko.tgbridge.Bridge.onInitialize$lambda$5(Bridge.kt:79) ~[transformed-mod-tgbridge.i0:0/:?]
        at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$6(ServerMessageEvents.java:102) ~[transformed-mod-fabric-message-api-v1.i0:0/:?]
        at net.minecraft.class_3324.handler$con000$onSendChatMessage(class_3324.java:6038) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.class_3324.method_43673(class_3324.java) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.class_1255.method_18857(class_1255.java:140) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:737) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.server.MinecraftServer.handler$edp000$modifiedRunLoop(MinecraftServer.java:12894) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:644) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[transformed-mod-minecraft-v1.19.2.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]`

**Comment by MeowBot233** [comment]
Are you using the right version of fabric API(or quilt API)? It seems that the error is from fabric API. I'm not familiar with quilt. Try use the same config on a fabric server.

**Comment by YukieMiona** [comment]
Cannot reproduce the problem. Tested on 1.19.3 server with bridge, kotlin, NCR and qfapi+qsl 4 mods installed. Quilt version 0.18.3. No obvious error occurs.
Try to change your mods' versions to reproduce the issue. More logs are required.

**Comment by MeowBot233** [comment]
The released version is built for 1.19.3+. If you need 1.19.2 version see #4
