### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by patpol4** [CuteNekoOwO/FabricTgBridge#4]
Are there any chances for a 1.19.2 version? I dont think the compatibility works backwards.

**Comment by MeowBot233** [comment]
All of this mod's functions (mc part) rely on fabric API. It would have a high chance of working with older Minecraft version as long as the latest fabric API is installed.
Mojang did add player message signature but reading messages from the server side is generally not affected.
Feel free to try it yourself and report any bug you encountered.

**Comment by patpol4** [comment]
When i load it and configure it with a api token and groupid, whenever someone on the server uses chat, it throws this error and the message doesnt show up ingame.:
<details>
<summary>Error</summary>
[Server thread/ERROR]: Chain link failed, continuing to next one
java.lang.NoSuchMethodError: 'net.minecraft.class_2561 net.minecraft.class_7471.method_46291()'
        at cuteneko.tgbridge.Bridge.onInitialize$lambda$5(Bridge.kt:79) ~[fabric_tg_bridge-1.0.0-all.jar:?]
        at net.fabricmc.fabric.api.message.v1.ServerMessageEvents.lambda$static$6(ServerMessageEvents.java:102) ~[fabric-message-api-v1-5.0.7+93d8cb8290-3132ad8077a566be.jar:?]
        at net.minecraft.class_3324.handler$daf000$fabric-message-api-v1$onSendChatMessage(class_3324.java:8038) ~[server-intermediary.jar:?]
        at net.minecraft.class_3324.method_43673(class_3324.java) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_44155(class_3244.java:1444) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_45064(class_3244.java:1302) ~[server-intermediary.jar:?]
        at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
        at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:776) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:159) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:758) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:752) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:736) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:669) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:257) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Thread.java:833) [?:?]
</details>
This is the fabric versions that i have
https://imgur.com/a/Z5M3rYp

**Comment by qyl27** [comment]
Yes, it should be reobf for 1.19.2, I have built a jar file for you, try this. (Don't forget unzip it to get a jar file.)
[fabric_tg_bridge-1.0.0-all.zip](https://github.com/CuteNekoOwO/FabricTgBridge/files/11600347/fabric_tg_bridge-1.0.0-all.zip)

**Comment by patpol4** [comment]
This worked and it appears to be functioning properly. Thanks a lot!
