### ISSUE TITLE
dont start mod

### ISSUE THREAD

**Issue by momai** [CuteNekoOwO/FabricTgBridge#5]
[16:21:31] [DefaultDispatcher-worker-2/ERROR]: Uncaught exception in thread "DefaultDispatcher-worker-2"
retrofit2.HttpException: HTTP 400
        at retrofit2.KotlinExtensions$await$2$2.onResponse(KotlinExtensions.kt:53) ~[fabric_tg_bridge-1.0.0-all.jar:?]
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:161) ~[fabric_tg_bridge-1.0.0-all.jar:?]
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174) ~[fabric_tg_bridge-1.0.0-all.jar:?]
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) ~[fabric_tg_bridge-1.0.0-all.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
        Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException

**mods:** fabric-api-0.82.0+1.19.4.jar  fabric-language-kotlin-1.9.4+kotlin.1.8.21.jar  fabric_tg_bridge-1.0.0-all.jar
**server:** fabric-server-mc.1.19.4-loader.0.14.21-launcher.0.11.2.jar

**Comment by MeowBot233** [comment]
Can you provide your config file plz? Remember to remove your bot token

**Comment by momai** [comment]
Wow, what a speed! Sure, here's the config.
```
at config/tgbridge/config.json
{
  "botToken": "---",
  "chatId": 6236652267,
  "telegramAPI": "api.telegram.org",
  "pollTimeout": 5,
  "sendChatMessage": true,
  "sendGameMessage": true,
  "sendTelegramMessage": true,
  "messageTrim": 20,
  "sendServerStarted": true,
  "sendServerStopping": true,
  "minecraftFormat": "<%1$s> %2$s",
  "telegramFormat": "<b>%1$s</b> %2$s",
  "serverStartedMessage": "Server has started!",
  "serverStoppingMessage": "Server is stopping!",
  "admins": [],
  "noPermission": "No permission!"

```

**Comment by MeowBot233** [comment]
Not sure about what's wrong🤔. I will make a new release containing more things for debugging soon

**Comment by momai** [comment]
Awesome! Thank you! Generally speaking, if needed, I'm readily available and prepared to provide all necessary data upon request. I can carry out required actions, including debugging and so on.

**Comment by MeowBot233** [comment]
Try this version and reproduce the bug, then provide detailed log.
[fabric_tg_bridge-1.0.0.zip](https://github.com/CuteNekoOwO/FabricTgBridge/files/11624250/fabric_tg_bridge-1.0.0.zip)

**Comment by momai** [comment]
Thank you so much!
It seems like the problem has been resolved. The mod is working, messages are being forwarded.
Here is the full server log, just in case (there are some error notifications in there).

``` cat logs/latest.log
[14:40:52] [main/INFO]: Loading Minecraft 1.19.4 with Fabric Loader 0.14.21
[14:40:52] [main/INFO]: Loading 54 mods:
        - fabric-api 0.82.0+1.19.4
           |-- fabric-api-base 0.4.26+1e9487d2f4
           |-- fabric-api-lookup-api-v1 1.6.27+504944c8f4
           |-- fabric-biome-api-v1 13.0.8+348a9c64f4
           |-- fabric-block-api-v1 1.0.7+e022e5d1f4
           |-- fabric-blockrenderlayer-v1 1.1.36+c2e6f674f4
           |-- fabric-client-tags-api-v1 1.0.17+504944c8f4
           |-- fabric-command-api-v1 1.2.29+f71b366ff4
           |-- fabric-command-api-v2 2.2.8+504944c8f4
           |-- fabric-commands-v0 0.2.46+df3654b3f4
           |-- fabric-containers-v0 0.1.56+df3654b3f4
           |-- fabric-content-registries-v0 3.5.11+ae0966baf4
           |-- fabric-convention-tags-v1 1.5.1+fe8721bef4
           |-- fabric-crash-report-info-v1 0.2.16+aeb40ebef4
           |-- fabric-data-generation-api-v1 11.4.2+504944c8f4
           |-- fabric-dimensions-v1 2.1.47+7f87f8faf4
           |-- fabric-entity-events-v1 1.5.15+504944c8f4
           |-- fabric-events-interaction-v0 0.5.1+76ba65ebf4
           |-- fabric-events-lifecycle-v0 0.2.54+df3654b3f4
           |-- fabric-game-rule-api-v1 1.0.34+a1ccd7bff4
           |-- fabric-item-api-v1 2.1.19+504944c8f4
           |-- fabric-item-group-api-v1 3.0.7+043f9acff4
           |-- fabric-key-binding-api-v1 1.0.34+504944c8f4
           |-- fabric-keybindings-v0 0.2.32+df3654b3f4
           |-- fabric-lifecycle-events-v1 2.2.17+1e9487d2f4
           |-- fabric-loot-api-v2 1.1.29+75e98211f4
           |-- fabric-loot-tables-v1 1.1.33+9e7660c6f4
           |-- fabric-message-api-v1 5.1.3+504944c8f4
           |-- fabric-mining-level-api-v1 2.1.41+49abcf7ef4
           |-- fabric-models-v0 0.3.32+504944c8f4
           |-- fabric-networking-api-v1 1.3.3+504944c8f4
           |-- fabric-networking-v0 0.3.43+df3654b3f4
           |-- fabric-object-builder-api-v1 7.0.5+504944c8f4
           |-- fabric-particles-v1 1.0.25+f1e4495bf4
           |-- fabric-recipe-api-v1 1.0.10+a1ccd7bff4
           |-- fabric-registry-sync-v0 2.2.2+504944c8f4
           |-- fabric-renderer-api-v1 2.3.0+52cca24ef4
           |-- fabric-renderer-indigo 1.3.0+52cca24ef4
           |-- fabric-renderer-registries-v1 3.2.40+df3654b3f4
           |-- fabric-rendering-data-attachment-v1 0.3.30+afca2f3ef4
           |-- fabric-rendering-fluids-v1 3.0.23+504944c8f4
           |-- fabric-rendering-v0 1.1.43+df3654b3f4
           |-- fabric-rendering-v1 2.1.3+504944c8f4
           |-- fabric-resource-conditions-api-v1 2.3.2+e6c7d4eef4
           |-- fabric-resource-loader-v0 0.11.4+5ade3c38f4
           |-- fabric-screen-api-v1 1.0.47+3bd4ab0ff4
           |-- fabric-screen-handler-api-v1 1.3.22+504944c8f4
           |-- fabric-sound-api-v1 1.0.10+504944c8f4
           |-- fabric-transfer-api-v1 3.2.0+80d07a0af4
           \-- fabric-transitive-access-wideners-v1 3.1.1+b4a333d6f4
        - fabric-language-kotlin 1.9.4+kotlin.1.8.21
           |-- org_jetbrains_kotlin_kotlin-reflect 1.8.21
           |-- org_jetbrains_kotlin_kotlin-stdlib 1.8.21
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.8.21
           |-- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.8.21
           |-- org_jetbrains_kotlinx_atomicfu-jvm 0.20.2
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4
           |-- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4
           |-- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.5.0
           |-- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.5.0
           \-- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.5.0
        - fabricloader 0.14.21
        - java 17
        - minecraft 1.19.4
        - tgbridge 1
[14:40:52] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/minecraft/vas3k/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[14:40:52] [main/INFO]: Compatibility level set to JAVA_16
[14:40:52] [main/INFO]: Compatibility level set to JAVA_17
[14:40:56] [main/INFO]: Telegram bridge loaded!
[14:40:57] [main/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[14:40:57] [main/INFO]: Found new data pack fabric, loading it automatically
[14:40:57] [main/INFO]: Loaded 7 recipes
[14:40:58] [main/INFO]: Loaded 1179 advancements
[14:40:58] [main/INFO]: Applied 0 biome modifications to 0 of 63 new biomes in 1.085 ms
[14:40:58] [Server thread/INFO]: Starting minecraft server version 1.19.4
[14:40:58] [Server thread/INFO]: Loading properties
[14:40:58] [Server thread/INFO]: Default game type: SURVIVAL
[14:40:58] [Server thread/INFO]: Generating keypair
[14:40:58] [Server thread/INFO]: Starting Minecraft server on *:25585
[14:40:58] [Server thread/INFO]: Using epoll channel type
[14:40:58] [Server thread/INFO]: Preparing level "world"
[14:40:59] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[14:41:00] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:01] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[14:41:01] [Worker-Main-8/INFO]: Preparing spawn area: 0%
[14:41:01] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:41:01] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:41:01] [Worker-Main-1/INFO]: Preparing spawn area: 0%
[14:41:02] [Worker-Main-10/INFO]: Preparing spawn area: 20%
[14:41:02] [Server thread/INFO]: Time elapsed: 2903 ms
[14:41:02] [Server thread/INFO]: Done (3.788s)! For help, type "help"
[14:41:03] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:06] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:09] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:12] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:13] [User Authenticator #1/INFO]: UUID of player momai is --
[14:41:13] [Server thread/INFO]: momai[/--:4630] logged in with entity id 149 at (168.88749894856034, 72.15760090177669, 106.90053484559483)
[14:41:13] [Server thread/INFO]: momai joined the game
[14:41:16] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:19] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:22] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:25] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:28] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:31] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:31] [User Authenticator #2/INFO]: UUID of playe-----
[14:41:32] [Server thread/INFO]: Belldandi joined the game
[14:41:34] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:37] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:39] [User Authenticator #3/INFO]: UUID of player----)
[14:41:40] [Server thread/INFO]: C0ffee_Gr0unds joined the game
[14:41:40] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:43] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:46] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:50] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:53] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:56] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:41:59] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:02] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:05] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:08] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:11] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:14] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:17] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:20] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:24] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:27] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:30] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:33] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:36] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:39] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:42] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:45] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:48] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:51] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:54] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:42:58] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:01] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:04] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:07] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:10] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:13] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:16] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:19] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:22] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:25] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:28] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:32] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:35] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:38] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:41] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:44] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:47] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:50] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:53] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:56] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:43:59] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:44:02] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:44:05] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:44:09] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
[14:44:12] [DefaultDispatcher-worker-2/ERROR]: HTTP 409
```

**Comment by MeowBot233** [comment]
Happy to know it works for you. 
Btw it seems that you have set webhook for your telegram bot which will prevent this mod from forwarding telegram message to Minecraft. If this is intended just set sendTelegramMessage to false in config file.
